### PR TITLE
Build notebook as well

### PR DESCRIPTION
**Pull request by devmotion**
Just requires to add
```julia
#md # [![](https://mybinder.org/badge_logo.svg)](@__BINDER_ROOT_URL__/filename_of_notebook.ipynb)
#md # [![](https://img.shields.io/badge/show-nbviewer-579ACA.svg)](@__NBVIEWER_ROOT_URL__/filename_of_notebook.ipynb)
```
to the top of the examples. Maybe it could even be automated?

I think it is better to wait for the updated examples instead of messing with the current versions, hence I marked it as WIP.

### CODE REVIEW

**Comment by devmotion** [comment]
Seems to work basically, links to the correct files such as https://nbviewer.jupyter.org/github/JuliaGaussianProcesses/AbstractGPs.jl/blob/gh-pages/previews/PR97/examples/regression_1d.ipynb. Just have to fix these `nothing` statements and some softscope warnings.

**Comment by devmotion** [comment]
OK, so this PR is ready for review. The badges are now added automatically only when the documentation is built. Moreover, I filtered some additional output in the documentation, improved the plots, and restricted the domain of the pseudo-points (the optimization was unstable with the modified random numbers after merging the examples). In the notebooks I included all outputs for now.

**Comment by devmotion** [comment]
The nbviewer page is outdated (apparently takes ~10 minutes until it is updated) but you can check the notebook version here as well: https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/gh-pages/previews/PR97/examples/regression_1d.ipynb

**Comment by willtebbutt** [comment]
It looks like loads of additional headings have been added in the docs that are built. Is it clear what's going on there?

**Comment by devmotion** [comment]
Additional headings?

**Comment by devmotion** [comment]
This PR only affects the example, and the headings there are untouched.

**Comment by willtebbutt** [comment]
Huh, weird. It's just that all of the font sizes on `Home` / `Features` are really large. Did this happen elsewhere and I just missed it?

**Comment by devmotion** [comment]
The home page looked always strange and unpolished: https://juliagaussianprocesses.github.io/AbstractGPs.jl/v0.2/

**Review by willtebbutt — APPROVED** [review]
Oooo okay, yes, it did. A job for another day. Anyway, this looks good!

**Pull request merged**
