### PR TITLE
Add documentation about the plotting

### PR DESCRIPTION
**Pull request by theogf**
Adresses #173 for the lack of documentation on plotting

### CODE REVIEW

**Comment by devmotion** [comment]
Could we maybe include the existing docstring of `sampleplot` (instead)? And add a docstring for `plot`?

**Comment by theogf** [comment]
Ok now I see it's quite overlapping with https://juliagaussianprocesses.github.io/AbstractGPs.jl/previews/PR174/examples/regression_1d/

How about I just put the docstrings in `Concrete Features` and that in the `Regression example` I add some of the kwargs (`ribbon_scale` and `samples`)?

**Comment by theogf** [comment]
@devmotion Do you know where `x` is  sorted before being used? I cannot find where it happens. It's nice but I am annoyed to not know where it's from

**Comment by devmotion** [comment]
AFAIK for some plot types Plots sorts stuff internally before plotting it.

**Comment by azev77** [comment]
Guys, the autoplot() function in forecast.R as a default plots 80% & 95% prediction intervals

https://pkg.robjhyndman.com/forecast/reference/plot.forecast.html

**Comment by devmotion** [comment]
That seems quite arbitrary :shrug: IMO this is more a documentation issue (which this PR addresses) than a problem with the default values.

**Comment by azev77** [comment]
But how is the current default choice of `μ ± 1.0σ` any less arbitrary than the more commonly used `μ ± 1.96σ`?

**Comment by willtebbutt** [comment]
I don't think it's more arbitrary either way. I personally have no strong feelings about it, but if we were change the defaults, we'd have to do it in the next breaking release. I can see the appeal of plotting 95% though 🤷

**Comment by theogf** [comment]
@devmotion I feel a bit dumb but I have no idea how to include the `plot` docstring...

**Pull request closed without merging**
