### PR TITLE
Add documentation preview

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Comment by willtebbutt** [comment]
Fantastic, thanks! Is it clear where to go to view the docs / could you add a comment in the GHA or something?

**Comment by devmotion** [comment]
You can view the preview build by pressing on the Github Action link below ("documenter/deploy - Documentation build succeeded").

**Comment by devmotion** [comment]
Do you think it needs a comment in the code or is it sufficiently clear?

**Comment by willtebbutt** [comment]
This is great. No I think it's probably fine -- if someone doesn't know how to do this it's sufficiently trivial to explain that I'm not too worried.

**Review by willtebbutt — APPROVED** [review]

**Comment by theogf** [comment]
@devmotion Could you do the same PR for KernelFunctions.jl ?

**Pull request merged**
