### PR TITLE
Soss test

### PR DESCRIPTION
**Pull request by cscherrer**
This PR adds a test for Soss. 

This doesn't work yet, because Turing and Soss have some name conflicts (at least `@model`). What do you think @theogf , I guess the tests for these systems could be in different modules? Or maybe just `import` instead of `using` and qualify all the names?

### CODE REVIEW

**Comment by devmotion** [comment]
> Or maybe just import instead of using and qualify all the names?

I'd prefer this approach.

**Comment by willtebbutt** [comment]
Somehow this got dropped. @cscherrer are you interested in reviving this PR? I'd very much like to get this in.

**Comment by devmotion** [comment]
I tried to update the PR to the new release of Soss some days ago (see https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/135) but unfortunately the tests error :cry:

**Comment by willtebbutt** [comment]
:( Maybe we should close this in favour of that one?

**Comment by devmotion** [comment]
Closed in favour of https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/135.

**Pull request closed without merging**
