### PR TITLE
Update Turing and Soss dependencies

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Review by willtebbutt — APPROVED** [review]
Looks like Distibutions@0.25 still isn't being used, but Turing, Soss, and SampleChainsDynamicsHMC have been updated, so I'm going to approve.

**Comment by theogf** [comment]
Since we just want to maintain compatibility with Turing and Soss do we really need to check `nightly` ?

**Comment by devmotion** [comment]
Only the standard CI uses nightly, Turing and Soss are only tested with the stable Julia version and only on linux.

**Comment by devmotion** [comment]
> Looks like Distibutions@0.25 still isn't being used, but Turing, Soss, and SampleChainsDynamicsHMC have been updated, so I'm going to approve.

Yes, I noticed this. I thought also we should drop old versions (Turing < 0.16 is not compatible with ChainRulesCore 0.10), so maybe let's stick with Distributions 0.24 for now and use the CompatHelper PR as a reminder that it should be updated eventually?

**Comment by theogf** [comment]
> Only the standard CI uses nightly, Turing and Soss are only tested with the stable Julia version and only on linux.

Oh right I read the CI wrong! :sweat_smile:

**Comment by devmotion** [comment]
Good to go?

**Review by theogf — APPROVED** [review]

**Pull request merged**
