### PR TITLE
Change author from Will to JuliaGaussianProcesses

### PR DESCRIPTION
**Pull request by theogf**
Or should I just remove the line (I saw Turing.jl and Flux.jl did)

### CODE REVIEW

**Comment by willtebbutt** [comment]
I have no strong opinion.

**Comment by willtebbutt** [comment]
@devmotion @sharanry do you have thoughts on this?

**Comment by devmotion** [comment]
I don't have a strong opinion on this one, but I think the PR is fine (I've seen the same approach e.g. in Distributions).

**Comment by sharanry** [comment]
Same here. No strong opinions. I think this PR is fine. I have never understood the role of the authors list. 😅

**Review by sharanry — APPROVED** [review]

**Review by willtebbutt — APPROVED** [review]
Cool. I'm happy to approve.

**Pull request merged**
