### PR TITLE
Bump CRC

### PR DESCRIPTION
**Pull request by willtebbutt**
Supercedes #190 and #191 .

### CODE REVIEW

**Comment by willtebbutt** [comment]
No idea whatsoever what's going on with the docs.

**Comment by willtebbutt** [comment]
For some reason the docs CI isn't able to find the new version of KernelFunctions -- not sure why that's happening. Will try again later.

**Comment by devmotion** [comment]
Maybe there's some problem with the package server right now and it serves an outdated registry? You could try to set  the environment variable `JULIA_PKG_SERVER` to an empty string, then it should download the registry with git.

**Comment by willtebbutt** [comment]
Looking promising. @devmotion unless you can think of anything else, I think this is probably good to go.

**Review by devmotion — APPROVED** [review]
LGTM, we can't do much about the failing PPL tests :shrug:

**Comment by willtebbutt** [comment]
Yeah. 🤞 they'll start working again at some point in the future without any intervention from us.

**Pull request merged**
