### PR TITLE
Corrects what appears to be an error in a docstring.

### PR DESCRIPTION
**Pull request by 4aHxKzD**

### CODE REVIEW

**Review by willtebbutt — APPROVED** [review]
Thanks for the fix! I'll merge once CI passes.

**Comment by willtebbutt** [comment]
@sharanry any idea what the CI error here is about?

**Comment by sharanry** [comment]
> @sharanry any idea what the CI error here is about?

Not sure. The errors are weird. It says `Base.contains` is missing. I have restarted the build to check it is a problem on travis side.

**Comment by devmotion** [comment]
`contains` requires Julia 1.5, so I guess it should be replaced with `occursin`.

**Comment by devmotion** [comment]
Tests errors should be fixed on master.

**Review by sharanry — APPROVED** [review]

**Pull request merged**
