### PR TITLE
use JuliaGPsDocs

### PR DESCRIPTION
**Pull request by st--**
**Summary**
Use [JuliaGPsDocs](https://github.com/JuliaGaussianProcesses/JuliaGPsDocs.jl/) in docs/make.jl

**NOTE**
I've updated the examples/README.md as in https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/pull/127 - but the corresponding file in https://github.com/JuliaGaussianProcesses/JuliaGPsDocs.jl/pull/8 hasn't been merged yet - so please let me know if you prefer to have that change as a separate PR.

### CODE REVIEW

**Comment by theogf** [comment]
Looks good! You could just add `Manifest.toml` in the `.gitignore` to avoid unfortunate commits.

**Comment by st--** [comment]
NOTE- I've updated the examples/README.md as in https://github.com/JuliaGaussianProcesses/ApproximateGPs.jl/pull/127 - but the corresponding file in https://github.com/JuliaGaussianProcesses/JuliaGPsDocs.jl/pull/8 hasn't been merged yet - so please let me know if you prefer to have that change as a separate PR.

**Comment by st--** [comment]
Requires https://github.com/JuliaGaussianProcesses/JuliaGPsDocs.jl/pull/12

**Review by willtebbutt — APPROVED** [review]
LGTM.

**Pull request merged**
