### PR TITLE
Replace `contains` with `occursin`

### PR DESCRIPTION
**Pull request by devmotion**
`contains` requires Julia >= 1.5.

### CODE REVIEW

**Review by willtebbutt — APPROVED** [review]

**Comment by willtebbutt** [comment]
Should probably have a patch version bump?

**Comment by devmotion** [comment]
Even though it just fixes a test error?

**Comment by willtebbutt** [comment]
Hmm yeah, maybe not. I don't have strong feelings either way.

**Comment by devmotion** [comment]
Hmm but yeah on a second thought, since users might actually want to run the tests a patch version bump might be appropriate.

**Review by theogf — APPROVED** [review]

**Comment by devmotion** [comment]
Seems we should add `print` statements to avoid time outs on MacOS?

**Pull request merged**
