### PR TITLE
Add support for FillArrays 0.11

### PR DESCRIPTION
**Pull request by devmotion**
Replaces https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/94.

### CODE REVIEW

**Comment by devmotion** [comment]
CI tests fail due to deprecation warnings in the doctests that are caused by the recent change from `kerneldiagmatrix` to `kernelmatrix_diag` in KernelFunctions 0.8.23. The doctests in the documentation pipeline do not fail since, apart from testing, julia does not show deprecation warnings.

Maybe we should remove the doctests from `runtests.jl`? It would be unfortunate to have to drop support for all releases of KernelFunctions apart from 0.8.23 just to update the definition of `cov_diag` (it seems `kerneldiagmatrix` is used only there).

**Comment by willtebbutt** [comment]
Eurgh, that is annoying. Would the fix not be to fix the deprecations?

**Comment by devmotion** [comment]
Yes, of course, one could update `cov_diag`. But then we would have to drop support for all previous versions of KernelFunctions.

> It would be unfortunate to have to drop support for all releases of KernelFunctions apart from 0.8.23 just to update the definition of cov_diag (it seems kerneldiagmatrix is used only there).

**Comment by willtebbutt** [comment]
True, but it seems to me that we're not able to utilise our doctests meaningfully in our CI while we've still got deprecation warnings -- am I missing something?

**Comment by devmotion** [comment]
No, that's correct - either we fix the deprecation warnings or remove doctests from `runtests.jl` (then they would be tested only in the documentation action).

**Comment by willtebbutt** [comment]
But it doesn't look like they're correctly causing the documentation action to fail when they fail, meaning that we'll probably not notice if the docstests are failing. Have I understood correctly?

**Comment by devmotion** [comment]
No, we will notice when the doctests fail. The only difference is that we run them with deprecation warnings being disabled (this is the default when we just call `julia -e ...`).

**Comment by willtebbutt** [comment]
Ohhhhhh I see. Could we just do that for the regular CI then, rather than move the doctests out of it?

**Comment by devmotion** [comment]
It seems (maybe) one can disable the deprecation warnings of the test action: https://github.com/julia-actions/julia-runtest/blob/b32c73084a913834335f8ff0ce6f6cad610a6fcf/action.yml#L18 AFAIK the tests will still fail locally though when e.g. run with `] test` since in this case deprecation warnings are enabled.

**Comment by willtebbutt** [comment]
Hmmm this is a bit frustrating. Seems like there are upsides and downsides either way 😬 @theogf what are your thoughts?

**Comment by theogf** [comment]
To be honest I did not get how changing to `kernelmatrix_diag` was not a breaking change and needed a version bump :) But that's irrelevant since this could happen from other packages as well.

If we notice failing in the docs that seems sufficient to me. They are **doc**tests after all :D

**Comment by devmotion** [comment]
I don't think there's a problem with the version numbers of KernelFunctions here. Adding deprecations is non-breaking, only their removal is breaking.

So you would remove the doctests from `runtests.jl` and only test them (without deprecation warnings) when building the documentation @theogf ?

**Pull request closed without merging**
